### ISSUE TITLE
Question regarding User Model getAll method.

### ISSUE THREAD

**Issue by tomshaw** [ezimuel/zend-expressive-api#16]
Is there an easy way to add $select->join/where/order to the App/User/UserModel getAll method?

**Comment by ezimuel** [comment]
You can select/where/order/group/having in UserModel::getAll() method passing the optional parameters to `DbTableGateway` [here](https://github.com/ezimuel/zend-expressive-api/blob/master/src/App/User/UserModel.php#L31) . For instance, you can apply a WHERE condition as follows:

```php
public function getAll(): Paginator
{
    $dbTableGatewayAdapter = new DbTableGateway($this->table, ['name' => 'Foo']);
    $paginator = new UserCollection($dbTableGatewayAdapter);
    return $paginator;
}
```
If you need to build a custom SQL I suggest to use the [Zend\Paginator\Adapter\DbSelect](https://docs.zendframework.com/zend-paginator/usage/#the-dbselect-adapter) class.

**Comment by tomshaw** [comment]
Thank you! This is a really neat example Expressive 3 application, saved me a lot of time learning. I especially like the RestDispatchTrait that proxies the http request methods. Awesome! Thanks again.
